[tool.poetry]
name = "pkgj-ci"
version = "0.1.0"
description = ""
authors = ["Philippe Daouadi <philippe@ud2.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
conan = "^2.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
